### ISSUE TITLE
SM weights 

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/ML4EFT#4]
Hi @wolfg259 , the following line takes the SM weights all equal to one, which might cause the mismatch you were mentioning via email?

https://github.com/LHCfitNikhef/ML4EFT/blob/f92604ae856b1772399dcf222f745063e767470e/code/src/ml4eft/core/classifier_.py#L449C9-L449C65

**Comment by wolfg259** [comment]
HI @jacoterh, the file classifier_.py is deprecated, the current version is classifier.py. I have removed all deprecated files following your comment, thanks for opening an issue!
